export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const RESET_INGREDIENTS = 'RESET_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BUILDER_START = 'PURCHASE_BUILDER_START';
export const PURCHASE_BUILDER_SUCCESS = 'PURCHASE_BUILDER_SUCCESS';
export const PURCHASE_BUILDER_FAIL = 'PURCHASE_BUILDER_FAIL';
